### ISSUE TITLE
Spurious warnings

### ISSUE THREAD

**Issue by kmzijadev** [rjbs/Sub-Install#4]
Esp when used with moose, this can emit a LOT of warnings at Sub/Install.pm:110
Should add `no warnings 'redefine';` to `sub _installer` somewhere.

**Comment by rjbs** [comment]
when using Sub::Install, one can choose to use a warning or non-warning form, via install_sub or reinstall_sub

In general, if you see these redefinition warnings on module load, it means that a module is being loaded twice, which means a circular loading.  That's the bug to fix, not the warning.
